modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
issueTrackerURL="https://github.com/MythrilBagels/Create-Alloyed/issues"
[[mods]]
    modId="alloyed"
    version="1.16.5"
    displayName="Create: Alloyed"
    #updateJSONURL="http://myurl.me/"
    displayURL="https://github.com/MythrilBagels/Create-Alloyed"
    logoFile="alloyed.png"
    credits="Thanks to the kind folks over on the Create and Create Modders Discord!"
    authors="Fortress Nebula, SpottyTheTurtle, and Bagels"
    description='''
    A Create addon adding Bronze and Steel, both items used for compatibility and decoration!
    '''

[[dependencies.alloyed]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.alloyed]]
    modId="create"
    mandatory=true
    versionRange="[mc1.16.5_v0.3.2f,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.alloyed]]
    modId="flywheel"
    mandatory=true
    versionRange="[1.16-0.2.4,1.16-0.3)"
    ordering="AFTER"
    side="CLIENT"
[[dependencies.alloyed]]
    modId="farmersdelight"
    mandatory=false
    versionRange="[1.16.5-0.5.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.alloyed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"