modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="alloyed"
version="1.16.5"
displayName="Create: Alloyed"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile="alloyed.png"
credits="yes"
authors="yes"
description='''
A Create addon adding Bronze and Steel, both items used for compatibility and decoration!
'''

[[dependencies.alloyed]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.alloyed]]
    modId="create"
    mandatory=true
    versionRange="[mc1.18.1_v0.4b,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.alloyed]]
    modId="flywheel"
    mandatory=true
    versionRange="[1.18-0.5.0,1.18-0.6.0)"
    ordering="AFTER"
    side="CLIENT"
[[dependencies.alloyed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1]"
    ordering="NONE"
    side="BOTH"