modLoader="javafml"
loaderVersion="[41,)"
license="MIT"
issueTrackerURL="https://github.com/MythrilBagels/Create-Alloyed/issues"
[[mods]]
modId="alloyed"
version="1.20.1"
displayName="Create: Alloyed"
#updateJSONURL="http://myurl.me/"
displayURL="https://github.com/MythrilBagels/Create-Alloyed"
logoFile="alloyed.png"
credits="Thanks to the kind folks over on the Create and Create Modders Discord!"
authors="Fortress Nebula, SpottyTheTurtle, and Bagels"
description='''
A Create addon adding Bronze and Steel, both items used for compatibility and decoration!
'''

[[dependencies.alloyed]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.alloyed]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.e,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.alloyed]]
    modId="farmersdelight"
    mandatory=false
    versionRange="[1.19-1.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.alloyed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"