modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/MythrilBagels/Create-Alloyed/issues"
[[mods]]
modId="alloyed"
version="1.18.2"
displayName="Create: Alloyed"
#updateJSONURL="http://myurl.me/"
displayURL="https://github.com/MythrilBagels/Create-Alloyed"
logoFile="alloyed.png"
credits="Thanks to the kind folks over on the Create and Create Modders Discord!"
authors="Fortress Nebula, SpottyTheTurtle, and Bagels"
description='''
A Create addon adding Bronze and Steel, both items used for compatibility and decoration!
'''

[[dependencies.alloyed]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.alloyed]]
    modId="create"
    mandatory=true
    versionRange="[mc1.18.2_v0.5.0e,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.alloyed]]
    modId="flywheel"
    mandatory=true
    versionRange="[0.6.5,)"
    ordering="AFTER"
    side="CLIENT"
[[dependencies.alloyed]]
    modId="farmersdelight"
    mandatory=false
    versionRange="[1.18.2-1.0.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.alloyed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"