modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="alloyed"
version="1.16.5"
displayName="Create: Composition"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile="alloyed.png"
credits="yes"
authors="yes"
description='''yes
'''
[[dependencies.alloyed]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.alloyed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"