modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
issueTrackerURL="https://github.com/MythrilBagels/Create-Alloyed/issues"
[[mods]]
modId="alloyed"
version="1.18.1"
displayName="Create: Alloyed"
#updateJSONURL="http://myurl.me/"
displayURL="https://github.com/MythrilBagels/Create-Alloyed"
logoFile="alloyed.png"
credits="Thanks to the kind folks over on the Create and Create Modders Discord!"
authors="Fortress Nebula, SpottyTheTurtle, and Bagels"
description='''
A Create addon adding Bronze and Steel, both items used for compatibility and decoration!
'''

[[dependencies.alloyed]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.alloyed]]
    modId="create"
    mandatory=true
    versionRange="[mc1.18.1_v0.4d,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.alloyed]]
    modId="flywheel"
    mandatory=true
    versionRange="[1.18-0.6.0,)"
    ordering="AFTER"
    side="CLIENT"
[[dependencies.alloyed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1]"
    ordering="NONE"
    side="BOTH"